services:
  # HTTP CONNECT Tunnel Proxy (Certificate-free) - Primary Service
  tunnel-proxy:
    build: .
    container_name: tunnel_proxy_server
    ports:
      - "10800:10800"  # Tunnel proxy port
    volumes:
      # Optional: Mount logs directory
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
      - PROXY_MODE=tunnel
    restart: unless-stopped
    networks:
      - proxy-network
    command: ["python", "start_tunnel_proxy.py", "--host", "0.0.0.0", "--port", "10800"]

volumes:
  mitmproxy-certs:
    name: mitmproxy_certificates

networks:
  proxy-network:
    driver: bridge