services:
  https-proxy:
    build: .
    container_name: https_proxy_server
    ports:
      - "8080:8080"  # Proxy port
      - "8081:8081"  # Web interface port
    volumes:
      # Mount certificates directory for persistence
      - mitmproxy-certs:/root/.mitmproxy
      # Optional: Mount logs directory
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
      # Optional: Add custom mitmproxy options
      - MITMPROXY_OPTS=
    restart: unless-stopped
    networks:
      - proxy-network

  # HTTP CONNECT Tunnel Proxy (Certificate-free)
  tunnel-proxy:
    build: .
    container_name: tunnel_proxy_server
    ports:
      - "8082:8080"  # Tunnel proxy port
    volumes:
      # Optional: Mount logs directory
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
      - PROXY_MODE=tunnel
    restart: unless-stopped
    networks:
      - proxy-network
    command: ["python", "start_tunnel_proxy.py", "--host", "0.0.0.0", "--port", "8080"]

volumes:
  mitmproxy-certs:
    name: mitmproxy_certificates

networks:
  proxy-network:
    driver: bridge